# Generated by Django 6.1 on 2026-08-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Student Status History',
                'verbose_name_plural': 'Student Status Histories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.statushistory',),
        ),
        migrations.CreateModel(
            name='StudentWalkInQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Student Walk-In Queue',
                'verbose_name_plural': 'Student Walk-In Queues',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('faculty.walkinqueue',),
        ),
    ]
