# Generated by Django 5.2 on 2026-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_seed_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('declined', 'Declined'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
    ]
