# Generated by Django 6.1 on 2026-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('consultation_request', 'Consultation request'), ('booking_confirmation', 'Booking confirmation'), ('announcement', 'Department announcement'), ('faculty_status_update', 'Faculty status update')], max_length=32),
        ),
    ]
