# Generated by Django 6.1 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('chairperson', 'Chairperson'), ('dean', 'Dean')], max_length=20, null=True),
        ),
    ]
