# Generated by Django 6.1 on 2026-08-21 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_consultation_student_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 21, 7, 27, 47, 663536, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
