# Generated by Django 6.1 on 2026-08-17 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_deptheadinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('closure_start', models.DateField(blank=True, null=True)),
                ('closure_end', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_closures_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
