# Generated by Django 6.1 on 2026-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptheadinvite',
            name='title',
            field=models.CharField(blank=True, choices=[('chairperson', 'Chairperson'), ('dean', 'Dean')], max_length=20, null=True),
        ),
    ]
