# Generated by Django 6.1 on 2026-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_college_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('consultation_request', 'Consultation request'), ('booking_confirmation', 'Booking confirmation'), ('announcement', 'College announcement'), ('faculty_status_update', 'Faculty status update')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('depthead', 'College Head'), ('superadmin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
