# Generated by Django 6.1.1 on 2026-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_notification_type_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeannouncement',
            name='audience',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('students', 'Students'), ('both', 'Both')], default='both', max_length=8),
        ),
    ]
