# Generated by Django 6.1 on 2026-08-10 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('faculty_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('department_id', models.CharField(db_column='department_id', max_length=64)),
                ('office_location', models.CharField(blank=True, max_length=128)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('virtual_only', 'Virtual Only'), ('on_leave', 'On Leave'), ('unavailable', 'Unavailable')], default='available', max_length=16)),
                ('status_note', models.TextField(blank=True)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_calendar_sync_at', models.DateTimeField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('request_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('faculty_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('busy', 'Busy'), ('unavailable', 'Unavailable'), ('on-leave', 'On Leave'), ('virtual', 'Virtual Only')], default='busy', max_length=16)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Schedule Event',
                'verbose_name_plural': 'Schedule Events',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('history_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('virtual_only', 'Virtual Only'), ('on_leave', 'On Leave'), ('unavailable', 'Unavailable')], max_length=16)),
                ('changed_at', models.DateTimeField()),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Status History',
                'verbose_name_plural': 'Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkInQueue',
            fields=[
                ('queue_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=16)),
                ('joined_at', models.DateTimeField()),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('student_message', models.TextField(blank=True)),
                ('faculty_note', models.TextField(blank=True)),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_queues', to='faculty.facultyprofile')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Walk-In Queue',
                'verbose_name_plural': 'Walk-In Queues',
                'ordering': ['position', 'joined_at'],
            },
        ),
    ]
