# Generated by Django 6.1 on 2026-08-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_facultyprofile_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
    ]
