# Generated by Django 6.1 on 2026-08-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_college_terminology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='college_id',
            field=models.CharField(db_column='college_id', max_length=64),
        ),
    ]
