# Generated by Django 6.1.1 on 2026-10-04 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_scheduleevent_occurrence_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSchedulerState',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('faculty_cursor', models.CharField(blank=True, max_length=64)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('accepted', 'Accepted by Brevo'), ('failed', 'Failed'), ('unknown', 'Outcome unknown'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='faculty.statushistory')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='status_email_pending_idx')],
                'constraints': [models.UniqueConstraint(fields=('history', 'recipient'), name='unique_status_email_recipient')],
            },
        ),
    ]
