# Generated by Django 6.1.1 on 2026-10-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0028_statusschedulerstate_statusemaildelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusemaildelivery',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
