# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollegeAIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_code", models.CharField(max_length=100, unique=True)),
                ("analytics_hash", models.CharField(max_length=64)),
                ("insights", models.JSONField()),
                ("model_name", models.CharField(max_length=100)),
                ("generated_at", models.DateTimeField()),
                ("refresh_after", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("college_code",)},
        ),
    ]
